version: "2"
services:
  mongo:
    container_name: mongo
    image: mongo
    #volumes:
      #- ./data:/data/db
    ports:
      - "27017:27017"
  app:
    container_name: app
    restart: "no"
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=integration
    links:
      - mongo
